CREATE TABLE massage_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    product_description TEXT NOT NULL,
    price numeric NOT NULL,
    product_image TEXT,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);
 
CREATE TABLE massage_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    email_address TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);