CREATE TABLE massage_wishlist (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wishlist_name TEXT NOT NULL
);

CREATE TABLE massage_wishlist_users (
    user_id INTEGER REFERENCES massage_users(id),
    wishlist_id INTEGER REFERENCES massage_wishlist(id),
    PRIMARY KEY(user_id, wishlist_id)
);

CREATE TABLE massage_wishlist_products (
    product_id INTEGER REFERENCES massage_products(id),
    wishlist_id INTEGER REFERENCES massage_wishlist(id),
    PRIMARY KEY(product_id, wishlist_id)
);